### ISSUE TITLE
changed value in JSON output should not be quoted

### ISSUE THREAD

**Issue by didfet** [pmarkham/writing-ansible-modules-in-bash#1]
I've developped a module based on your example and I've noticed that the value of the changed property in the JSON output of the script should not be quoted.
For example "changed":"false" is interpreted by ansible as "changed":"true"

Thank you for sharing your work anyway.

**Comment by pmarkham** [comment]
I changed the text of the document, but hadn't changed the sample code. I'll fix it and upload a new copy.

Thanks for the feedback!
